import {
  ServiceItem,
  PortfolioItem,
  ThreadColor,
  PricingPlan,
  TrackedOrder,
  Testimonial,
  FAQItem,
} from '../types';

import embroideryHeroImg from '../assets/images/embroidery_hero_1785789323266.jpg';
import vectorArtImg from '../assets/images/vector_art_showcase_1785789338757.jpg';
import patchesShowcaseImg from '../assets/images/patches_showcase_1785789353075.jpg';

export const HERO_IMAGE = embroideryHeroImg;
export const VECTOR_SHOWCASE_IMAGE = vectorArtImg;
export const PATCHES_SHOWCASE_IMAGE = patchesShowcaseImg;

export const SERVICES_DATA: ServiceItem[] = [
  {
    id: 'embroidery-digitizing',
    title: 'Custom Embroidery Digitizing',
    category: 'digitizing',
    shortDesc: 'Precision embroidery files engineered for seamless stitching on any commercial or home embroidery machine.',
    fullDesc: 'We convert your artwork into high-quality embroidery files (.DST, .PES, .EXP, .EMB) with optimized stitch density, minimal thread breaks, and perfect push-and-pull compensation for caps, jackets, polos, and beanies.',
    iconName: 'Needle',
    startingPrice: '$10 Flat',
    turnaround: '2 - 6 Hours',
    features: [
      'Cap & Left Chest Logo Digitizing',
      '3D Puff & Foam Embroidery',
      'Jacket Back & Oversized Designs',
      'Applique & Chenille Digitizing',
      'Test Stitched on Real Machines',
      'Free Revisions & Format File Conversions',
    ],
    image: embroideryHeroImg,
  },
  {
    id: 'vector-artwork',
    title: 'Vector Artwork Conversion',
    category: 'vector',
    shortDesc: 'Convert low-resolution images, hand sketches, or blurry JPEGs into clean, scalable vector graphics.',
    fullDesc: 'Our vector art specialists manually redraw and vectorize artwork into crisp AI, EPS, SVG, and high-res PDF files perfect for screen printing, vinyl cutting, sublimation, signage, and laser engraving.',
    iconName: 'PenTool',
    startingPrice: '$10 Flat',
    turnaround: '2 - 8 Hours',
    features: [
      'Raster to Clean Vector Tracing',
      'Color Separations for Screen Printing',
      'Logo Redrawing & Cleanup',
      'CMYK / Pantone PMS Color Matching',
      '100% Scalable Resolution Independent',
      'Ready for Print & Vinyl Plotting',
    ],
    image: vectorArtImg,
  },
  {
    id: 'custom-patches',
    title: 'Custom Patches Manufacturing',
    category: 'patches',
    shortDesc: 'Premium custom embroidered, woven, PVC rubber, and leather laser-engraved patches with custom backings.',
    fullDesc: 'Order custom physical patches made with top-tier thread and durable backings (Iron-on, Velcro hook & loop, Adhesive, or Sew-on). Ideal for military uniforms, motorcycle clubs, streetwear, and corporate caps.',
    iconName: 'ShieldCheck',
    startingPrice: '$1.20 / patch',
    turnaround: '3 - 5 Days',
    features: [
      'Embroidered & Woven Fabric Patches',
      'PVC / Rubber Waterproof 3D Patches',
      'Genuine & Synthetic Leather Patches',
      'Iron-On, Velcro & Adhesive Backings',
      'Merrowed & Cut-to-Shape Borders',
      'Free Physical Sample Approval',
    ],
    image: patchesShowcaseImg,
  },
];

export const PORTFOLIO_DATA: PortfolioItem[] = [
  {
    id: 'port-1',
    title: '3D Puff Golden Eagle Cap Logo',
    category: '3d-puff',
    placement: 'Flexfit / Richardson Cap Front',
    stitches: 12450,
    colors: 3,
    beforeImage: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
    afterImage: embroideryHeroImg,
    description: 'Custom 3D foam puff digitizing on cap front. Features high stitch density, clean satin columns, and center-out cap sequencing for maximum stability.',
    formats: ['.DST', '.PES', '.EMB', '.EXP', '.JEF'],
  },
  {
    id: 'port-2',
    title: 'Vibrant Mascot Vector Redraw',
    category: 'vector',
    placement: 'Screen Printing & T-Shirt Sublimation',
    beforeImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    afterImage: vectorArtImg,
    description: 'Converted a pixelated phone screenshot into crisp, fully scalable EPS and AI artwork with precise node placement and Pantone PMS color separation.',
    formats: ['.AI', '.EPS', '.SVG', '.PDF', '.PNG'],
  },
  {
    id: 'port-3',
    title: 'Custom Tactical & Outdoor Patches',
    category: 'patches',
    placement: 'Velcro Hook-and-Loop Backing',
    stitches: 18200,
    colors: 6,
    beforeImage: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    afterImage: patchesShowcaseImg,
    description: 'Heavy-duty tactical patch featuring merrowed border edges, high thread density fill, and durable heat-sealed backing.',
    formats: ['.DST', '.EMB', '.AI', '.PDF'],
  },
  {
    id: 'port-4',
    title: 'Motorcycle Club Jacket Back Eagle',
    category: 'embroidery',
    placement: 'Leather Jacket Back Center',
    stitches: 68400,
    colors: 8,
    beforeImage: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80',
    description: 'Oversized 12-inch jacket back digitizing with layered fill stitches, smooth gradient blending, and zero puckering on leather.',
    formats: ['.DST', '.PES', '.EXP', '.VP3', '.HUS'],
  },
  {
    id: 'port-5',
    title: 'Corporate Polo Left Chest Logo',
    category: 'embroidery',
    placement: 'Pique Polo Left Chest',
    stitches: 7200,
    colors: 4,
    beforeImage: 'https://images.unsplash.com/photo-1618354691229-88d47f285158?auto=format&fit=crop&w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    description: 'Clean micro-text digitizing down to 4mm height, crisp sharp lettering, and underlay structure tailored for stretchy pique fabric.',
    formats: ['.DST', '.PES', '.EMB', '.EXP'],
  },
  {
    id: 'port-6',
    title: 'Vintage Crest & Shield Vector Art',
    category: 'vector',
    placement: 'Embroidery & Print Graphics',
    beforeImage: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80',
    afterImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=800&q=80',
    description: 'Intricate crest design re-drawn with symmetrical curves, clean color layering, and ready for vinyl plotting or screen print separation.',
    formats: ['.AI', '.EPS', '.SVG', '.CDR', '.PDF'],
  },
];

export const THREAD_COLORS: ThreadColor[] = [
  { brand: 'Madeira Classic', code: '1000', name: 'Super White', hex: '#FFFFFF', category: 'Whites' },
  { brand: 'Madeira Classic', code: '1002', name: 'Snow White', hex: '#F8F9FA', category: 'Whites' },
  { brand: 'Madeira Classic', code: '1005', name: 'Jet Black', hex: '#111111', category: 'Blacks' },
  { brand: 'Madeira Classic', code: '1037', name: 'Scarlet Red', hex: '#D32F2F', category: 'Reds' },
  { brand: 'Madeira Classic', code: '1147', name: 'Crimson Red', hex: '#B71C1C', category: 'Reds' },
  { brand: 'Madeira Classic', code: '1025', name: 'Royal Navy', hex: '#0D47A1', category: 'Blues' },
  { brand: 'Madeira Classic', code: '1134', name: 'Cobalt Blue', hex: '#1976D2', category: 'Blues' },
  { brand: 'Madeira Polyneon', code: '1800', name: 'Emerald Green', hex: '#2E7D32', category: 'Greens' },
  { brand: 'Madeira Polyneon', code: '1970', name: 'Goldenrod', hex: '#F57F17', category: 'Yellows' },
  { brand: 'Madeira Polyneon', code: '1725', name: 'Vibrant Orange', hex: '#EF6C00', category: 'Oranges' },
  { brand: 'Madeira Polyneon', code: '1735', name: 'Metallic Gold', hex: '#D4AF37', category: 'Metallics' },
  { brand: 'Madeira Polyneon', code: '1738', name: 'Metallic Silver', hex: '#C0C0C0', category: 'Metallics' },
  { brand: 'Isacord', code: '0010', name: 'Isacord White', hex: '#FCFCFC', category: 'Whites' },
  { brand: 'Isacord', code: '0020', name: 'Isacord Black', hex: '#050505', category: 'Blacks' },
  { brand: 'Isacord', code: '1902', name: 'Isacord Fire Red', hex: '#E53935', category: 'Reds' },
  { brand: 'Isacord', code: '3540', name: 'Isacord Deep Blue', hex: '#1565C0', category: 'Blues' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'price-cap-chest',
    name: 'Cap & Left Chest',
    category: 'digitizing',
    price: '$10',
    unit: 'flat rate (up to 10k stitches)',
    popular: true,
    description: 'Perfect for front cap logos, left chest polo logos, beanies, and sleeves.',
    features: [
      'Up to 10,000 stitches included',
      'Free minor edits & stitch adjustments',
      'All machine formats (.DST, .PES, .EXP, etc.)',
      '2 to 6 hours fast delivery option',
      'PDF stitch sheet & thread chart',
      '100% test-stitched quality check',
    ],
    turnaround: '2-6 Hours',
  },
  {
    id: 'price-jacket-back',
    name: 'Jacket Back & Large',
    category: 'digitizing',
    price: '$35',
    unit: 'flat rate (or $1.20/k over 30k)',
    description: 'Ideal for full jacket backs, biker patches, hoodies, and giant tote logos.',
    features: [
      'Up to 30,000 stitches included',
      'Layered fill density management',
      'Leather & heavy fabric underlay optimization',
      'Free unlimited minor revisions',
      'Full sequence color stops list',
      'Dedicated senior digitizer handling',
    ],
    turnaround: '4-12 Hours',
  },
  {
    id: 'price-vector-standard',
    name: 'Standard Vector Art',
    category: 'vector',
    price: '$10',
    unit: 'per artwork design',
    popular: true,
    description: 'Convert logos, badges, and simple graphics into clean print-ready vector files.',
    features: [
      'Raster to Vector manual redraw',
      '100% scalable vector files (.AI, .EPS, .SVG)',
      'High-res transparent PNG & PDF export',
      'CMYK / RGB / Pantone color mode',
      'Free color separation on request',
      'Same-day express delivery',
    ],
    turnaround: '2-8 Hours',
  },
  {
    id: 'price-vector-complex',
    name: 'Complex Vector Art',
    category: 'vector',
    price: '$20 - $35',
    unit: 'per complex design',
    description: 'Detailed illustrations, intricate mascots, fine line artwork, and vintage crests.',
    features: [
      'Manual curve node optimization',
      'Intricate shading & gradient meshes',
      'Screen print separation files',
      'Vinyl plotter ready cutlines',
      'Source files in multiple formats',
      'Priority turnaround',
    ],
    turnaround: '4-12 Hours',
  },
  {
    id: 'price-patches-custom',
    name: 'Custom Patch Batch',
    category: 'patches',
    price: '$1.20',
    unit: 'per patch (min qty 25)',
    description: 'Physical custom embroidered, woven, or PVC patches delivered to your door.',
    features: [
      'Free digital proof & digitizing included',
      'Choice of Iron-on, Velcro or Adhesive',
      'Merrowed or laser-cut borders',
      'Up to 10 thread colors included',
      'Free worldwide express shipping',
      '100% inspection guarantee',
    ],
    turnaround: '5-7 Days',
  },
];

export const SAMPLE_TRACKED_ORDERS: TrackedOrder[] = [
  {
    orderId: 'GP-84920',
    clientEmail: 'john@customembroidery.com',
    designName: 'Apex Tactical Cap Logo',
    serviceType: '3D Puff Digitizing',
    dateSubmitted: '2026-08-03 09:15 AM',
    status: 'Quality Check & Test Stitch',
    estimatedCompletion: 'Today at 02:30 PM',
    previewImage: embroideryHeroImg,
    downloadFormats: ['.DST', '.PES', '.EMB', '.PDF'],
    stitches: 11200,
    colors: 3,
    dimensions: '2.4" W x 2.1" H',
  },
  {
    orderId: 'GP-84918',
    clientEmail: 'sarah@printdesign.com',
    designName: 'Falcon Crest Vector Conversion',
    serviceType: 'Vector Art Redraw',
    dateSubmitted: '2026-08-03 08:00 AM',
    status: 'Completed',
    estimatedCompletion: 'Completed',
    previewImage: vectorArtImg,
    downloadFormats: ['.AI', '.EPS', '.SVG', '.PDF'],
    stitches: 0,
    colors: 4,
    dimensions: 'Scalable Vector',
  },
  {
    orderId: 'GP-84912',
    clientEmail: 'mike@bikerclubapparel.org',
    designName: 'Lone Wolf Jacket Back',
    serviceType: 'Jacket Back Digitizing',
    dateSubmitted: '2026-08-02 04:45 PM',
    status: 'Completed',
    estimatedCompletion: 'Completed',
    previewImage: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80',
    downloadFormats: ['.DST', '.EXP', '.EMB', '.VP3', '.PDF'],
    stitches: 54200,
    colors: 7,
    dimensions: '11.5" W x 12.8" H',
  },
];

export const TESTIMONIALS_DATA: Testimonial[] = [
  {
    id: 't-1',
    clientName: 'David Miller',
    company: 'StitchCraft Apparel Co.',
    role: 'Owner & Chief Embroiderer',
    rating: 5,
    comment: 'Graphics Punching is hands down the best digitizing service we have used in 15 years. Their cap digitizing stitches smoothly with zero thread breaks, even on tough 3D puff designs. The 3-hour turnaround saved my rush order!',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    location: 'Texas, USA',
  },
  {
    id: 't-2',
    clientName: 'Elena Rostova',
    company: 'Vanguard Screen Printing',
    role: 'Art Director',
    rating: 5,
    comment: 'We send all our low-res client artwork to Graphics Punching for vectorization. Their lines are surgical, colors match Pantone perfectly, and the pricing is unbeatable at $10. Fantastic team!',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    location: 'Toronto, Canada',
  },
  {
    id: 't-3',
    clientName: 'Marcus Vance',
    company: 'Ironclad Headwear & Gear',
    role: 'Production Manager',
    rating: 5,
    comment: 'The test stitching worksheets and preview files give our team complete confidence before mounting caps on our Tajima machines. Never had a single customer reject a logo digitized by them.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    location: 'Manchester, UK',
  },
];

export const FAQ_DATA: FAQItem[] = [
  {
    question: 'What embroidery machine formats do you provide?',
    answer: 'We provide all standard machine formats including Tajima (.DST), Brother/Babylock (.PES), Melco (.EXP), Wilcom (.EMB), Janome (.JEF), Pfaff (.VP3 / .PCS), Husqvarna (.HUS), Singer (.XXX), and Barudan (.DAT). If you need any specific format, simply mention it in your order notes!',
    category: 'Formats & Machines',
  },
  {
    question: 'How fast will I receive my completed digitizing or vector file?',
    answer: 'Our standard turnaround is 4 to 8 hours. If you need super rush delivery, select our 2 to 4 hour express service. We operate 24/7 with dedicated day and night digitizing shifts.',
    category: 'General',
  },
  {
    question: 'Do you charge for minor edits or size adjustments?',
    answer: 'No! Minor revisions, thread color changes, small size tweaks (up to 15%), and machine format conversions are 100% FREE unlimited within 30 days of your order.',
    category: 'Digitizing',
  },
  {
    question: 'How do you calculate digitizing pricing?',
    answer: 'For standard cap logos and left chest logos (up to 10,000 stitches), we charge a flat rate of $10. For larger jacket backs and complex oversized crests, we offer a $35 flat rate up to 30,000 stitches or $1.20 per 1,000 stitches for massive designs.',
    category: 'Payment',
  },
  {
    question: 'What is 3D Puff embroidery digitizing?',
    answer: '3D Puff digitizing uses specialized foam under the embroidery thread to create raised, three-dimensional lettering or logos commonly seen on high-end streetwear caps. We sequence the stitches to cleanly cap off foam edges so no raw foam sticks through.',
    category: 'Digitizing',
  },
  {
    question: 'What file formats are delivered for Vector Artwork orders?',
    answer: 'You will receive vector source files in Adobe Illustrator (.AI), Encapsulated PostScript (.EPS), Scalable Vector Graphics (.SVG), Print PDF, and high-resolution transparent PNG images.',
    category: 'Vector',
  },
];
